### ISSUE TITLE
USB Scan not detecting arduino

### ISSUE THREAD

**Issue by elliottcoe** [createcandle/Candle-manager-addon#13] opened 2020-05-21 17:10 UTC
I have an Arduino Uno, and Raspberry PI 4.

I have followed the instructions, and it just seems to not be able to detect the arduino when it is connected.

I have tried using a different USB port, rebooting the Pi and reinstalling the addon, when I check the network tab in Chrome, I only see this as a response in the UsbScan request:

{
  "port_id": [], 
  "state": "stable"
}

**Comment by createcandle** [comment] 2020-06-17 11:30
I have a suspicion what the issue is. It should be fixed in the next version.

**Comment by createcandle** [comment] 2020-12-06 18:00
If the issue wasn't fixed, feel free to re-open this issue.

**Closed as completed by createcandle** 2020-12-06 18:00 UTC
